name: Rust static build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build for all platforms
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      BINARY_NAME: rust-test1
    steps:
      - uses: actions/checkout@v2
      - name: install cross-rs
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: build
        run: |
          cross build --target aarch64-unknown-linux-musl
          cross build --target i586-unknown-linux-musl
          cross build --target x86_64-unknown-linux-musl
          cross build --target i686-pc-windows-gnu
          cross build --target x86_64-pc-windows-gnu

