name: Rust static build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build for all platforms
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - name: install cross-rs
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: build
        run: |
          cross build --release --target aarch64-unknown-linux-musl
          cross build --release --target i686-unknown-linux-musl
          cross build --release --target x86_64-unknown-linux-musl
          cross build --release --target i686-pc-windows-gnu
          cross build --release --target x86_64-pc-windows-gnu

      - uses: actions/upload-artifact@v4
        with:
          name: nsv.exe
          path: ./target/x86_64-pc-windows-gnu/release/lerna-rust.exe

